### ISSUE TITLE
TypeError is raised while running detection on more than one event through bug in "compute_metrics_dataset.py"

### ISSUE THREAD

**Issue by swickner** [Dreem-Organization/dosed#20]
When the dataset contains more than one event, running the training step first raises a VisibleDeprecationWarning and then a TypeError from Python: 
- ...\Python\Python38\lib\site-packages\numpy\core\_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray => return array(a, dtype, copy=False, order=order, subok=True)
- ...\Python\Python38\lib\site-packages\numpy\core\fromnumeric.py:87: TypeError: can only concatenate list (not "int") to list. 

This occurs through a bug in the file _dosed/dosed/functions/compute_metrics_dataset.py_ where only the metrics for the last event in the event list are averaged, whereas the metrics for the other events stay unchanged.

Original code (lines 62 to 70):
```python
# If for any event and record the network predicted events, return -1
if found_some_events is False:
    return -1

for metric in metrics.keys():
    metrics_test[event_num][metric] = np.nanmean(
        np.array(metrics_test[event_num][metric]))

return metrics_test
```

The average should be calculated for each of the events instead:
```python
# If for any event and record the network predicted events, return -1
if found_some_events is False:
    return -1

for event_num in range(network.number_of_classes - 1):
    for metric in metrics.keys():
        metrics_test[event_num][metric] = np.nanmean(np.array(metrics_test[event_num][metric]))

return metrics_test
```

**Comment by agramfort** [comment]
@vthorey @slasnista do you have time to look?

**Comment by vthorey** [comment]
This is a valid suggestion thanks for reporting it ;)

**Comment by vthorey** [comment]
Your suggested changes were integrated.
